import { CategoryData, Category } from "./types";

export const allCategories: CategoryData[] = [
    { id: Category.ACTION, title: "Action" },
    { id: Category.ADVENTURE, title: "Adventure" },
    { id: Category.ANIMATION, title: "Animation" },
    { id: Category.BIOGRAPHY, title: "Biography" },
    { id: Category.COMEDY, title: "Comedy" },
    { id: Category.CRIME, title: "Crime" },
    { id: Category.DOCUMENTARY, title: "Documentary" },
    { id: Category.DRAMA, title: "Drama" },
    { id: Category.FAMILY, title: "Family" },
    { id: Category.FANTASY, title: "Fantasy" },
    { id: Category.FILM_NOIR, title: "Film Noir" },
    { id: Category.GAME_SHOW, title: "Game Show" },
    { id: Category.HISTORY, title: "History" },
    { id: Category.HORROR, title: "Horror" },
    { id: Category.MUSIC, title: "Music" },
    { id: Category.MUSICAL, title: "Musical" },
    { id: Category.MYSTERY, title: "Mystery" },
    { id: Category.NEWS, title: "News" },
    { id: Category.REALITY_TV, title: "Reality TV" },
    { id: Category.ROMANCE, title: "Romance" },
    { id: Category.SCI_FI, title: "Sci-Fi" },
    { id: Category.SPORT, title: "Sport" },
    { id: Category.TALK_SHOW, title: "Talk Show" },
    { id: Category.THRILLER, title: "Thriller" },
    { id: Category.WAR, title: "War" },
    { id: Category.WESTERN, title: "Western" },
    { id: Category.SUPERHERO, title: "Superhero" },
    { id: Category.SLICE_OF_LIFE, title: "Slice of Life" },
    { id: Category.ANTHOLOGY, title: "Anthology" },
    { id: Category.ESPIONAGE, title: "Espionage" },
    { id: Category.TEEN, title: "Teen" },
    { id: Category.HOLIDAY, title: "Holiday" },
    { id: Category.SATIRE, title: "Satire" },
    { id: Category.PARODY, title: "Parody" },
    { id: Category.TRAGEDY, title: "Tragedy" },
    { id: Category.MEDICAL, title: "Medical" },
    { id: Category.POLITICAL, title: "Political" },
    { id: Category.MILITARY, title: "Military" },
    { id: Category.LEGAL, title: "Legal" },
    { id: Category.POST_APOCALYPTIC, title: "Post-Apocalyptic" },
    { id: Category.CYBERPUNK, title: "Cyberpunk" },
    { id: Category.DYSTOPIAN, title: "Dystopian" },
    { id: Category.GHOST, title: "Ghost" },
    { id: Category.ZOMBIE, title: "Zombie" },
    { id: Category.SUPER_NATURAL, title: "Supernatural" },
    { id: Category.KIDS, title: "Kids" },
    { id: Category.CULT_CLASSIC, title: "Cult Classic" },
    { id: Category.DARK_COMEDY, title: "Dark Comedy" },
    { id: Category.PERIOD_DRAMA, title: "Period Drama" },
    { id: Category.ROAD_TRIP, title: "Road Trip" },
    { id: Category.TIME_TRAVEL, title: "Time Travel" },
    { id: Category.SPACE_OPERA, title: "Space Opera" },
    { id: Category.BIOPUNK, title: "Biopunk" }
];