export enum Category {
    ACTION = "action",
    ADVENTURE = "adventure",
    ANIMATION = "animation",
    BIOGRAPHY = "biography",
    COMEDY = "comedy",
    CRIME = "crime",
    DOCUMENTARY = "documentary",
    DRAMA = "drama",
    FAMILY = "family",
    FANTASY = "fantasy",
    FILM_NOIR = "film_noir",
    GAME_SHOW = "game_show",
    HISTORY = "history",
    HORROR = "horror",
    MUSIC = "music",
    MUSICAL = "musical",
    MYSTERY = "mystery",
    NEWS = "news",
    REALITY_TV = "reality_tv",
    ROMANCE = "romance",
    SCI_FI = "sci_fi",
    SPORT = "sport",
    TALK_SHOW = "talk_show",
    THRILLER = "thriller",
    WAR = "war",
    WESTERN = "western",
    SUPERHERO = "superhero",
    SLICE_OF_LIFE = "slice_of_life",
    ANTHOLOGY = "anthology",
    ESPIONAGE = "espionage",
    TEEN = "teen",
    HOLIDAY = "holiday",
    SATIRE = "satire",
    PARODY = "parody",
    TRAGEDY = "tragedy",
    MEDICAL = "medical",
    POLITICAL = "political",
    MILITARY = "military",
    LEGAL = "legal",
    POST_APOCALYPTIC = "post_apocalyptic",
    CYBERPUNK = "cyberpunk",
    DYSTOPIAN = "dystopian",
    GHOST = "ghost",
    ZOMBIE = "zombie",
    SUPER_NATURAL = "super_natural",
    KIDS = "kids",
    CULT_CLASSIC = "cult_classic",
    DARK_COMEDY = "dark_comedy",
    PERIOD_DRAMA = "period_drama",
    ROAD_TRIP = "road_trip",
    TIME_TRAVEL = "time_travel",
    SPACE_OPERA = "space_opera",
    BIOPUNK = "biopunk"
}

export type CategoryData = {
    id: Category;
    title: string;
}