import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/components/query-provider";
import { cn } from "@/lib/utils";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US">
      <head>
        <link rel="icon" type="image/x-icon" href="/logo.svg"/>
      </head>
      <body
        className={cn("dark antialiased", inter.className)}
      >
        <SessionProvider>
          <QueryProvider>
            <NuqsAdapter>
              <Toaster />
              {children}
            </NuqsAdapter>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
